export const productActions = {
  ITEMS_LOADED: "ITEMS_LOADED",
  ITEM_ADDED_TO_CART: "ITEM_ADDED_TO_CART",
  REMOVE_ITEM_FROM_CART: "REMOVE_ITEM_FROM_CART",
  DECREMENT_ITEM_IN_CART: "DECREMENT_ITEM_IN_CART",
};
